# Generated by Django 5.2.4 on 2025-08-06 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numar', models.CharField(max_length=20)),
                ('nume', models.CharField(max_length=255)),
                ('tip_cont', models.CharField(choices=[('A', 'Activ'), ('P', 'Pasiv')], default='A', max_length=1)),
                ('firma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.firma')),
            ],
            options={
                'unique_together': {('firma', 'numar')},
            },
        ),
        migrations.CreateModel(
            name='Operatiune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descriere', models.TextField()),
                ('suma', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cont_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operatiuni_credit', to='app.cont')),
                ('cont_debit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operatiuni_debit', to='app.cont')),
                ('firma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.firma')),
            ],
        ),
    ]
