# Generated by Django 5.2.4 on 2025-08-06 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cont',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cont',
            name='numar',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='operatiune',
            name='firma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.firma'),
        ),
        migrations.RemoveField(
            model_name='cont',
            name='firma',
        ),
        migrations.RemoveField(
            model_name='cont',
            name='tip_cont',
        ),
    ]
